version: 0.0
os: linux

files:
  - source: ./webapp/target/java-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/webapp

hooks:
  BeforeInstall:
   - location: ./infrastructure/aws/codedeploy/before-install.sh
     timeout: 300
     runas: ubuntu
