version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu

permissions:
  - object: /home/ubuntu/java-0.0.1-SNAPSHOT.jar
    pattern: "*.jar"
    owner: root
    mode: 777
    type:
      - file
hooks:

  AfterInstall:
   - location: /infrastructure/aws/codedeploy/after-install.sh
     timeout: 300
     runas: ubuntu