version: 2
jobs:
  build:
    working_directory: ~/webapp
    filter:
      branches:
        only:
          - Assignment7
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install -y python-pip
      #- run:
       #   name: Install awscli
       #   command: sudo pip install awscli
      - run: 
          name: Build package
          command: pwd && sudo apt install maven && mvn package
     # - run:
     #     name: Build zip
      #    command: |
      #      pwd
       #     ls -al
       #     mvn package
      # - run:
       #    name: CODEDEPLOY API call
        #   command: |
         #    aws deploy create-deployment \
          #   --application-name ${CODEDEPLOY_APPLICATION_NAME} \
           #  --deployment-config-name CodeDeployDefault.AllAtOmce \
            # --deployment-group-name ${CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME} \
             #--description "CSYE6225 - CodeDeploy" \
             #--s3-location bucket=${S3_CODEDEPLOY_BUCKET},key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip,bundleType=zip \
             #--region us-east-1 \
             #--output json
             
         
            
            
          
            
      
