version: 2
jobs:
  build:
    working_directory: ~/webapp
    filter:
      branches:
        only:
          - Assignment7
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install -y python-pip
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run: 
          name: Build package
          command: pwd && ls -al && cd webapp && sudo apt install maven && mvn package
      - run:
          name: Build Deployment Artifact
          command: mkdir codedeploy_artifact && zip -r csye6225-webapp-${CIRCLE_BUILD_NUM}.zip webapp/target/java-0.0.1-SNAPSHOT.jar infrastructure/aws/codedeploy/*.sh appspec.yml && mv csye6225-webapp-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
      - run:
          name: Validate zip
          command: cd codedeploy_artifact && pwd && ls -al
      - run:
          name: Copy Artifact to S3
          command: aws s3 sync ./codedeploy_artifact s3://${S3_CODEDEPLOY_BUCKET}

      - run:
          name: CODEDEPLOY API call
          command: |
            echo "Hello CodeDeploy"
            aws deploy create-deployment\
              --region us-east-1\
              --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE\
              --application-name ${CODEDEPLOY_APPLICATION_NAME}\
              --deployment-config-name CodeDeployDefault.OneAtATime\
              --deployment-group-name ${CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME}\
              --s3-location bucket=${S3_CODEDEPLOY_BUCKET},bundleType=zip,key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip
             
         
            
            
          
            
      
